name: Todo Creeper 
description: Identify as TODOs creep into a project's code 

inputs:
  token:
    description: GitHub token for API access
    required: true
    default: ${{ github.token }}
  
  threshold:
    description: Maximum number of TODOs allowed before action fails
    required: false
    default: '10'
  
  exclude-patterns:
    description: Comma-separated patterns to exclude from TODO search
    required: false
    default: 'node_modules,dist,build,.git'
  
  create-issues:
    description: Whether to create GitHub issues for TODOs without associated issues
    required: false
    default: 'false'
  
  issue-labels:
    description: Comma-separated labels to apply to created issues
    required: false
    default: 'todo,enhancement'

outputs:
  todo-count:
    description: Total number of TODOs found
  todo-files:
    description: Number of files containing TODOs
  todo-details:
    description: Detailed TODO information
  issues-created:
    description: Number of new issues created
  issues-linked:
    description: Number of TODOs linked to existing issues

runs:
  using: node20
  main: dist/index.js

