name: Test TODO Creeper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-todo-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build action
        run: npm run build
      
      - name: Test TODO scan
        id: todo-scan
        uses: ./
        with:
          threshold: 5
          exclude-patterns: 'node_modules,dist,build,.git'
      
      - name: Display results
        run: |
          echo "TODO count: ${{ steps.todo-scan.outputs.todo-count }}"
          echo "Files with TODOs: ${{ steps.todo-scan.outputs.todo-files }}"
